List planetDetails = [
  {
    "planetName": "Earth",
    "distanceToEarth": "0",
    "distanceToSun": "150.31 m km",
    "overView":"Our home planet Earth is a rocky, terrestrial planet. It has a solid and active surface with mountains, valleys, canyons, plains and so much more. Earth is special because it is an ocean planet. Water covers 70 percent of Earth's surface. \n\n Earth's atmosphere is made mostly of nitrogen and has plenty of oxygen for us to breathe. The atmosphere also protects us from incoming meteoroids, most of which break up before they can hit the surface.",
    "planetImage": "assets/images/earth.png",
    "surfaceImage":"assets/images/surface_images/earth.jpg",
    "gravity" : "9.807",
  },
  {
    "planetName": "Mars",
    "distanceToEarth": "129.7 m km",
    "distanceToSun": "145.66 m km",
    "overView":"Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. ... Mars is a terrestrial planet with a thin atmosphere, with surface features reminiscent of the impact craters of the Moon and the valleys, deserts and polar ice caps of Earth.",
    "planetImage": "assets/images/mars.png",
    "surfaceImage":"assets/images/surface_images/mars.jpg",
    "gravity" : "3.721",
  },
  {
    "planetName": "Mercury",
    "distanceToEarth": "197.84 m km",
    "distanceToSun": "27.857 m km",
    "overView":"Mercury is the smallest planet in our solar system. ... Along with Venus, Earth, and Mars, Mercury is one of the rocky planets. It has a solid surface that is covered with craters. It has no atmosphere, and it doesn't have any moons.",
    "planetImage": "assets/images/mercury.png",
    "surfaceImage":"assets/images/surface_images/mercury.jpg",
    "gravity" : "3.7",
  },
  {
    "planetName": "Moon",
    "distanceToEarth": "384,400 km",
    "distanceToSun": "150 m km",
    "overView":"The Moon is Earth's only natural satellite and the fifth largest moon in the solar system. The Moon's presence helps stabilize our planet's wobble, which helps stabilize our climate. The Moon's distance from Earth is about 240,000 miles (385,000km). The Moon has a very thin atmosphere called an exosphere.",
    "planetImage": "assets/images/moon.png",
    "surfaceImage":"assets/images/surface_images/moon.jpg",
    "gravity" : "1.62",
  },
  {
    "planetName": "Neptune",
    "distanceToEarth": "4.5919 b km",
    "distanceToSun": "4.4756 b km",
    "overView":"Neptune is very similar to Uranus. It's made of a thick soup of water, ammonia, and methane over an Earth-sized solid center. Its atmosphere is made of hydrogen, helium, and methane. The methane gives Neptune the same blue color as Uranus.",
    "planetImage": "assets/images/neptune.png",
    "surfaceImage":"assets/images/surface_images/neptune.webp",
    "gravity" : "11.15",
  },
];